LEFT_HAND:
- ACTION_NAME: 张开
  ACTION_POS:
  - 255
  - 175
  - 255
  - 255
  - 255
  - 255
  - 72
- ACTION_NAME: 握拳
  ACTION_POS:
  - 70
  - 116
  - 0
  - 0
  - 0
  - 0
  - 46
- ACTION_NAME: 食指弯曲
  ACTION_POS:
  - 255
  - 175
  - 0
  - 255
  - 255
  - 255
  - 72
- ACTION_NAME: 中指弯曲
  ACTION_POS:
  - 255
  - 175
  - 0
  - 0
  - 255
  - 255
  - 72
- ACTION_NAME: 无名指弯曲
  ACTION_POS:
  - 255
  - 175
  - 0
  - 0
  - 0
  - 255
  - 72
- ACTION_NAME: 小拇指弯曲
  ACTION_POS:
  - 255
  - 175
  - 0
  - 0
  - 0
  - 0
  - 72
- ACTION_NAME: 大拇指弯曲
  ACTION_POS:
  - 13
  - 125
  - 250
  - 250
  - 250
  - 250
  - 32
RIGHT_HAND:
- ACTION_NAME: 张开
  ACTION_POS:
  - 255
  - 175
  - 255
  - 255
  - 255
  - 255
  - 72
- ACTION_NAME: 握拳
  ACTION_POS:
  - 70
  - 116
  - 0
  - 0
  - 0
  - 0
  - 46
- ACTION_NAME: 食指弯曲
  ACTION_POS:
  - 255
  - 175
  - 0
  - 255
  - 255
  - 255
  - 72
- ACTION_NAME: 中指弯曲
  ACTION_POS:
  - 255
  - 175
  - 0
  - 0
  - 255
  - 255
  - 72
- ACTION_NAME: 无名指弯曲
  ACTION_POS:
  - 255
  - 175
  - 0
  - 0
  - 0
  - 255
  - 72
- ACTION_NAME: 小拇指弯曲
  ACTION_POS:
  - 255
  - 175
  - 0
  - 0
  - 0
  - 0
  - 72
- ACTION_NAME: 大拇指弯曲
  ACTION_POS:
  - 13
  - 125
  - 250
  - 250
  - 250
  - 250
  - 32